# Generated by Django 3.1.3 on 2020-11-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 50, 5, 794239)),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 50, 5, 794239)),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
